#215 Improve access of __annotations__.
databricks/databricks-sdk-py pull request #239
Opened 2023-07-17 23:10 UTC by MichaelSpece

## Changes
This is a continuation of #216, but with signed, verified commits.

## Tests
One test was added (in #216).  The last run in #216 passed all tests.

- [ ] `make test` run locally
- [ ] `make fmt` applied
- [ ] relevant integration tests applied

2023-07-17 23:12 UTC, MichaelSpece commented
@nfx GitHub was complaining about unsigned commits so I resynced my fork, which closed #216.

2023-07-18 09:57 UTC, nfx requested changes
this looks like too big of a change, can't accept it.

please make sure the PR holds diff only for the relevant changes. most likely the newline characters are changed or something like it.

2023-07-18 15:11 UTC, MichaelSpece commented
@nfx Ok; the line endings had indeed been modified.  I have now rebased with auto handling of line endings and the diff is showing a relatively small difference.

2023-07-18 15:11 UTC, nfx requested changes

2023-07-18 15:11 UTC, nfx commented on tests/test_core.py
> +    test_config_accounts_dod_is_accounts_host(conftest.config.__pytest_wrapped__.obj())
these seem irrelevant

2023-07-26 09:37 UTC, merged