fix windows path (#661)
databricks/databricks-sdk-py pull request #673
Opened 2024-06-11 13:26 UTC by parthban-db

## Changes

Changed `pathlib.Path` with the `pathlib.PurePosixPath` in `/databricks/sdk/mixins/files.py` which always use linux path separators regardless of the OS that it is running on.

## Tests

- [ ] `make test` run locally
- [ ] `make fmt` applied
- [ ] relevant integration tests applied

2024-06-12 14:03 UTC, edwardfeng-db commented on databricks/sdk/mixins/files.py
> +        self._system_path = pathlib.Path(self._path)
It'd be good to add a comment explaining why we need `self._path` to be `PurePosixPath` and why we need `self._system_path`

2024-06-12 14:05 UTC, edwardfeng-db commented
Can you link the github issue that this PR solves in the PR description?

2024-06-13 11:37 UTC, edwardfeng-db approved these changes
LGTM, let's get @mgyucht to take a look before merging

2024-06-13 22:29 UTC, mgyucht requested changes
Thank you for your contribution @parthban-db! A couple notes about this PR:

The more I think about this, the more I think we're putting too much implementation detail in one place. I would do the following:
1. Change `_Path.__init__` to be an `@abstractmethod` and remove its implementation.
2. Add `__init__` implementations in each of `_DbfsPath`, `_LocalPath` and `_VolumesPath`. In `_DbfsPath` and `_VolumesPath`, use `PurePosixPath`, and in `_LocalPath` use `Path`.
This way, we don't duplicate the `path` state, and each implementation can choose the specific path type needed for itself.

Second: We should also make sure we add a test case that covers the actual issue reported by the user: when making a directory in DBFS, regardless of the OS, the path separator used in the API call must be `/`, not `\`. 

@edwardfeng-db could you help @parthban-db modify the unit test runners to support testing in Windows as well?

2024-07-02 14:30 UTC, mgyucht reviewed
LGTM once you add the volumes test

2024-07-02 14:30 UTC, mgyucht commented on tests/test_dbfs_mixins.py
> +def test_dbfs_exists(config, mocker):
Can we do this test for volumes as well?

2024-07-03 07:56 UTC, mgyucht approved these changes

2024-07-03 08:31 UTC, merged